// Code generated by protoc-gen-go. DO NOT EDIT.
// source: loggingStream.proto

package logginStream

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type LogRequest struct {
	Logfile              string   `protobuf:"bytes,1,opt,name=logfile,proto3" json:"logfile,omitempty"`
	Filter               string   `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogRequest) Reset()         { *m = LogRequest{} }
func (m *LogRequest) String() string { return proto.CompactTextString(m) }
func (*LogRequest) ProtoMessage()    {}
func (*LogRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_loggingStream_42ee9a0bd611f10a, []int{0}
}
func (m *LogRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogRequest.Unmarshal(m, b)
}
func (m *LogRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogRequest.Marshal(b, m, deterministic)
}
func (dst *LogRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogRequest.Merge(dst, src)
}
func (m *LogRequest) XXX_Size() int {
	return xxx_messageInfo_LogRequest.Size(m)
}
func (m *LogRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogRequest proto.InternalMessageInfo

func (m *LogRequest) GetLogfile() string {
	if m != nil {
		return m.Logfile
	}
	return ""
}

func (m *LogRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

// The response message containing the greetings
type LogResponse struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	CreateAt             string   `protobuf:"bytes,2,opt,name=createAt,proto3" json:"createAt,omitempty"`
	Content              string   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Status               int32    `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogResponse) Reset()         { *m = LogResponse{} }
func (m *LogResponse) String() string { return proto.CompactTextString(m) }
func (*LogResponse) ProtoMessage()    {}
func (*LogResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_loggingStream_42ee9a0bd611f10a, []int{1}
}
func (m *LogResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogResponse.Unmarshal(m, b)
}
func (m *LogResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogResponse.Marshal(b, m, deterministic)
}
func (dst *LogResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogResponse.Merge(dst, src)
}
func (m *LogResponse) XXX_Size() int {
	return xxx_messageInfo_LogResponse.Size(m)
}
func (m *LogResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LogResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LogResponse proto.InternalMessageInfo

func (m *LogResponse) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *LogResponse) GetCreateAt() string {
	if m != nil {
		return m.CreateAt
	}
	return ""
}

func (m *LogResponse) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *LogResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func init() {
	proto.RegisterType((*LogRequest)(nil), "logginStream.LogRequest")
	proto.RegisterType((*LogResponse)(nil), "logginStream.LogResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LoggingStreamClient is the client API for LoggingStream service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LoggingStreamClient interface {
	// Sends a greeting
	SendLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (LoggingStream_SendLogClient, error)
}

type loggingStreamClient struct {
	cc *grpc.ClientConn
}

func NewLoggingStreamClient(cc *grpc.ClientConn) LoggingStreamClient {
	return &loggingStreamClient{cc}
}

func (c *loggingStreamClient) SendLog(ctx context.Context, in *LogRequest, opts ...grpc.CallOption) (LoggingStream_SendLogClient, error) {
	stream, err := c.cc.NewStream(ctx, &_LoggingStream_serviceDesc.Streams[0], "/logginStream.LoggingStream/SendLog", opts...)
	if err != nil {
		return nil, err
	}
	x := &loggingStreamSendLogClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LoggingStream_SendLogClient interface {
	Recv() (*LogResponse, error)
	grpc.ClientStream
}

type loggingStreamSendLogClient struct {
	grpc.ClientStream
}

func (x *loggingStreamSendLogClient) Recv() (*LogResponse, error) {
	m := new(LogResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LoggingStreamServer is the server API for LoggingStream service.
type LoggingStreamServer interface {
	// Sends a greeting
	SendLog(*LogRequest, LoggingStream_SendLogServer) error
}

func RegisterLoggingStreamServer(s *grpc.Server, srv LoggingStreamServer) {
	s.RegisterService(&_LoggingStream_serviceDesc, srv)
}

func _LoggingStream_SendLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LogRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggingStreamServer).SendLog(m, &loggingStreamSendLogServer{stream})
}

type LoggingStream_SendLogServer interface {
	Send(*LogResponse) error
	grpc.ServerStream
}

type loggingStreamSendLogServer struct {
	grpc.ServerStream
}

func (x *loggingStreamSendLogServer) Send(m *LogResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _LoggingStream_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logginStream.LoggingStream",
	HandlerType: (*LoggingStreamServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SendLog",
			Handler:       _LoggingStream_SendLog_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "loggingStream.proto",
}

func init() { proto.RegisterFile("loggingStream.proto", fileDescriptor_loggingStream_42ee9a0bd611f10a) }

var fileDescriptor_loggingStream_42ee9a0bd611f10a = []byte{
	// 245 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x31, 0x94, 0x16, 0x0e, 0x10, 0x92, 0x91, 0x90, 0x29, 0x4b, 0x95, 0xa9, 0x93, 0x55,
	0xc1, 0x8e, 0x44, 0x26, 0x86, 0x0c, 0x55, 0x32, 0x30, 0x87, 0xf4, 0x6a, 0x22, 0xb9, 0x3e, 0x63,
	0x5f, 0x05, 0xfc, 0x7b, 0xe4, 0x24, 0x85, 0x0c, 0x6c, 0xef, 0xbb, 0xd3, 0xd3, 0xbb, 0x77, 0x70,
	0x63, 0xc9, 0x98, 0xd6, 0x99, 0x8a, 0x03, 0xd6, 0x3b, 0xed, 0x03, 0x31, 0xc9, 0xcb, 0x7e, 0xd8,
	0xcf, 0xb2, 0x27, 0x80, 0x82, 0x4c, 0x89, 0x1f, 0x7b, 0x8c, 0x2c, 0x15, 0xcc, 0x2c, 0x99, 0x6d,
	0x6b, 0x51, 0x89, 0x85, 0x58, 0x9e, 0x97, 0x07, 0x94, 0xb7, 0x30, 0xdd, 0xb6, 0x96, 0x31, 0xa8,
	0xe3, 0x6e, 0x31, 0x50, 0x46, 0x70, 0xd1, 0xf9, 0xa3, 0x27, 0x17, 0x51, 0x4a, 0x98, 0xf0, 0xb7,
	0x3f, 0xb8, 0x3b, 0x2d, 0xe7, 0x70, 0xd6, 0x04, 0xac, 0x19, 0x9f, 0x79, 0x30, 0xff, 0x72, 0x0a,
	0x6c, 0xc8, 0x31, 0x3a, 0x56, 0x27, 0x7d, 0xe0, 0x80, 0x29, 0x30, 0x72, 0xcd, 0xfb, 0xa8, 0x26,
	0x0b, 0xb1, 0x3c, 0x2d, 0x07, 0x7a, 0xa8, 0xe0, 0xaa, 0x18, 0xb7, 0x92, 0x39, 0xcc, 0x2a, 0x74,
	0x9b, 0x82, 0x8c, 0x54, 0x7a, 0xdc, 0x4d, 0xff, 0x15, 0x9b, 0xdf, 0xfd, 0xb3, 0xe9, 0x4f, 0xce,
	0x8e, 0x56, 0x22, 0x5f, 0xc1, 0x7d, 0x4b, 0xda, 0x04, 0xdf, 0x68, 0xfc, 0xaa, 0x77, 0xde, 0x62,
	0xd4, 0xef, 0x68, 0x2d, 0x7d, 0x52, 0xb0, 0x9b, 0xfc, 0xfa, 0x25, 0xe9, 0xd7, 0xa4, 0xd7, 0xe9,
	0x87, 0x6b, 0xf1, 0x36, 0xed, 0x9e, 0xf9, 0xf8, 0x13, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xe7, 0xaa,
	0xdc, 0x63, 0x01, 0x00, 0x00,
}
